# Creating a logistic regression to predict absenteeism

## Import the relevant libraries

In [4]:
# import the relevant libraries
import pandas as pd
import numpy as np

## Load the data

In [5]:
# load the preprocessed CSV data
data_preprocessed = pd.read_csv('Absenteeism_data_preprocessed.csv')

In [6]:
# eyeball the data
data_preprocessed.head()

Reason 1  Reason 2  Reason 3  Reason 4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

## Create the targets

In [7]:
# find the median of 'Absenteeism Time in Hours'
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [8]:
# create targets for our logistic regression
# they have to be categories and we must find a way to say if someone is 'being absent too much' or not
# what we've decided to do is to take the median of the dataset as a cut-off line
# in this way the dataset will be balanced (there will be roughly equal number of 0s and 1s for the logistic regression)
# as balancing is a great problem for ML, this will work great for us
# alternatively, if we had more data, we could have found other ways to deal with the issue 
# for instance, we could have assigned some arbitrary value as a cut-off line, instead of the median

# note that what line does is to assign 1 to anyone who has been absent 4 hours or more (more than 3 hours)
# that is the equivalent of taking half a day off

# initial code from the lecture
# targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

# parameterized code
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [9]:
# eyeball the targets
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [10]:
# create a Series in the original data frame that will contain the targets for the regression
data_preprocessed['Excessive Absenteeism'] = targets

In [11]:
# check what happened
# maybe manually see how the targets were created
data_preprocessed.head()

Reason 1  Reason 2  Reason 3  Reason 4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [12]:
# check if dataset is balanced (what % of targets are 1s)
# targets.sum() will give us the number of 1s that there are
# the shape[0] will give us the length of the targets array
targets.sum() / targets.shape[0]

0.45571428571428574

In [13]:
# create a checkpoint by dropping the unnecessary variables
# also drop the variables we 'eliminated' after exploring the weights
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

In [14]:
# check if the line above is a checkpoint :)

# if data_with_targets is data_preprocessed = True, then the two are pointing to the same object
# if it is False, then the two variables are completely different and this is in fact a checkpoint
data_with_targets is data_preprocessed

False

In [15]:
# check what's inside
data_with_targets.head()

Reason 1  Reason 2  Reason 3  Reason 4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Month Value  Day of the week  Excessive Absenteeism  
0         2     1            7                1                      1  
1         1     0            7                1                      0  
2         0     0            7                2                      0  
3         2     0            7                3                      1  
4         2     1            7                3                      0

## Select the inputs for the regression

In [16]:
data_with_targets.shape

(700, 15)

In [17]:
# Selects all rows and all columns until 14 (excluding)
data_with_targets.iloc[:,:14]

Reason 1  Reason 2  Reason 3  Reason 4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Month Value  Day of the week  
0            0         2     1            7                1  
1            0         1     0            7                1  
2            0         0     0            7                2  
3            0         2     0            7                3  
4            0         2     1            7                3  
..         ...       ...   ...          ...              ...  
695          1         2     0            5                2  
696          0         1     2            5                2  
697          1         0     0            5                3  
698          1         0     0            5                3  
699          0         1     1            5                3  

[700 rows x 14 columns]

In [18]:
# Selects all rows and all columns but the last one (basically the same operation)
data_with_targets.iloc[:,:-1]

Reason 1  Reason 2  Reason 3  Reason 4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Month Value  Day of the week  
0            0         2     1            7                1  
1            0         1     0            7                1  
2            0         0     0            7                2  
3            0         2     0            7                3  
4            0         2     1            7                3  
..         ...       ...   ...          ...              ...  
695          1         2     0            5                2  
696          0         1     2            5                2  
697          1         0     0            5                3  
698          1         0     0            5                3  
699          0         1     1            5                3  

[700 rows x 14 columns]

In [19]:
# Create a variable that will contain the inputs (everything without the targets)
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [20]:
# standardize the inputs

# standardization is one of the most common preprocessing tools
# since data of different magnitude (scale) can be biased towards high values,
# we want all inputs to be of similar magnitude
# this is a peculiarity of machine learning in general - most (but not all) algorithms do badly with unscaled data

# a very useful module we can use is StandardScaler 
# it has much more capabilities than the straightforward 'preprocessing' method
from sklearn.preprocessing import StandardScaler


# we will create a variable that will contain the scaling information for this particular dataset
# here's the full documentation: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

# define scaler as an object
absenteeism_scaler = StandardScaler()

In [21]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [22]:
# check what are all columns that we've got
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the week'], dtype=object)

In [23]:
# choose the columns to scale
# we later augmented this code and put it in comments
# columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
    
# select the columns to omit
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [24]:
# create the columns to scale, based on the columns to omit
# use list comprehension to iterate over the list
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [25]:
# declare a scaler object, specifying the columns you want to scale
absenteeism_scaler = CustomScaler(columns_to_scale)

C:\Users\---\anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [26]:
# fit the data (calculate mean and standard deviation); they are automatically stored inside the object 
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\---\anaconda3\lib\site-packages\sklearn\base.py:209: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  warnings.warn('From version 0.24, get_params will raise an '


CustomScaler(columns=['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4',
                      'Transportation Expense', 'Distance to Work', 'Age',
                      'Daily Work Load Average', 'Body Mass Index', 'Children',
                      'Pets', 'Month Value', 'Day of the week'],
             copy=None, with_mean=None, with_std=None)

In [27]:
# standardizes the data, using the transform method 
# in the last line, we fitted the data - in other words
# we found the internal parameters of a model that will be used to transform data. 
# transforming applies these parameters to our data
# note that when you get new data, you can just call 'scaler' again and transform it in the same way as now
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [28]:
# the scaled_inputs are now an ndarray, because sklearn works with ndarrays
scaled_inputs

Reason 1  Reason 2  Reason 3  Reason 4  Transportation Expense  \
0   -0.577350 -0.092981 -0.314485  0.821365                1.005844   
1   -0.577350 -0.092981 -0.314485 -1.217485               -1.574681   
2   -0.577350 -0.092981 -0.314485  0.821365               -0.654143   
3    1.732051 -0.092981 -0.314485 -1.217485                0.854936   
4   -0.577350 -0.092981 -0.314485  0.821365                1.005844   
..        ...       ...       ...       ...                     ...   
695  1.732051 -0.092981 -0.314485 -1.217485               -0.654143   
696  1.732051 -0.092981 -0.314485 -1.217485                0.040034   
697  1.732051 -0.092981 -0.314485 -1.217485                1.624567   
698 -0.577350 -0.092981 -0.314485  0.821365                0.190942   
699 -0.577350 -0.092981 -0.314485  0.821365                1.036026   

     Distance to Work       Age  Daily Work Load Average  Body Mass Index  \
0            0.412816 -0.536062                -0.806331         0.767431   
1           -1.141882  2.130803                -0.806331         1.002633   
2            1.426749  0.248310                -0.806331         1.002633   
3           -1.682647  0.405184                -0.806331        -0.643782   
4            0.412816 -0.536062                -0.806331         0.767431   
..                ...       ...                      ...              ...   
695         -0.533522  0.562059                -0.853789        -1.114186   
696         -0.263140 -1.320435                -0.853789        -0.643782   
697         -0.939096 -1.320435                -0.853789        -0.408580   
698         -0.939096 -0.692937                -0.853789        -0.408580   
699          0.074838  0.562059                -0.853789        -0.408580   

     Education  Children      Pets  Month Value  Day of the week  
0            0  0.880469  0.268487     0.182726        -0.683704  
1            0 -0.019280 -0.589690     0.182726        -0.683704  
2            0 -0.919030 -0.589690     0.182726        -0.007725  
3            0  0.880469 -0.589690     0.182726         0.668253  
4            0  0.880469  0.268487     0.182726         0.668253  
..         ...       ...       ...          ...              ...  
695          1  0.880469 -0.589690    -0.388293        -0.007725  
696          0 -0.019280  1.126663    -0.388293        -0.007725  
697          1 -0.919030 -0.589690    -0.388293         0.668253  
698          1 -0.919030 -0.589690    -0.388293         0.668253  
699          0 -0.019280  0.268487    -0.388293         0.668253  

[700 rows x 14 columns]

In [29]:
# check the shape of the inputs
scaled_inputs.shape

(700, 14)

## Split the data into train & test and shuffle

### Import the relevant module

In [30]:
# import train_test_split so we can split our data into train and test
from sklearn.model_selection import train_test_split

### Split

In [31]:
# check how this method works
train_test_split(scaled_inputs, targets)

[     Reason 1  Reason 2  Reason 3  Reason 4  Transportation Expense  \
 88  -0.577350 -0.092981 -0.314485  0.821365                0.040034   
 426 -0.577350 -0.092981 -0.314485  0.821365                0.387122   
 399 -0.577350 -0.092981 -0.314485  0.821365                2.092381   
 282 -0.577350 -0.092981 -0.314485  0.821365                0.568211   
 307 -0.577350 -0.092981 -0.314485  0.821365                1.036026   
 ..        ...       ...       ...       ...                     ...   
 592 -0.577350 -0.092981 -0.314485  0.821365                0.040034   
 517 -0.577350 -0.092981 -0.314485  0.821365                2.213108   
 339  1.732051 -0.092981 -0.314485 -1.217485                0.040034   
 284 -0.577350 -0.092981 -0.314485  0.821365               -1.574681   
 657 -0.577350 -0.092981  3.179797 -1.217485                0.387122   
 
      Distance to Work       Age  Daily Work Load Average  Body Mass Index  \
 88          -0.263140 -1.320435                 0.86372

In [32]:
# declare 4 variables for the split
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [33]:
# check the shape of the train inputs and targets
print (x_train.shape, y_train.shape)

(560, 14) (560,)


In [34]:
# check the shape of the test inputs and targets
print (x_test.shape, y_test.shape)

(140, 14) (140,)


## Logistic regression with sklearn

In [35]:
# import the LogReg model from sklearn
from sklearn.linear_model import LogisticRegression

# import the 'metrics' module, which includes important metrics we may want to use
from sklearn import metrics

### Training the model

In [36]:
# create a logistic regression object
reg = LogisticRegression()

In [37]:
# fit our train inputs
# that is basically the whole training part of the machine learning
reg.fit(x_train,y_train)

LogisticRegression()

In [38]:
# assess the train accuracy of the model
reg.score(x_train,y_train)

0.7839285714285714

### Manually check the accuracy

In [39]:
# find the model outputs according to our model
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [40]:
# compare them with the targets
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [41]:
# ACTUALLY compare the two variables
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [42]:
# find out in how many instances we predicted correctly
np.sum((model_outputs==y_train))

439

In [43]:
# get the total number of instances
model_outputs.shape[0]

560

In [44]:
# calculate the accuracy of the model
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7839285714285714

### Finding the intercept and coefficients

In [45]:
# get the intercept (bias) of our model
reg.intercept_

array([-0.1669092])

In [46]:
# get the coefficients (weights) of our model
reg.coef_

array([[ 2.07452606,  0.33355827,  1.55923   ,  1.32893272,  0.70486037,
        -0.03682454, -0.19993103, -0.00319661,  0.3227044 , -0.3323036 ,
         0.38398576, -0.33216428,  0.18893894, -0.07135387]])

In [47]:
# check what were the names of our columns
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the week'], dtype=object)

In [48]:
# save the names of the columns in an ad-hoc variable
feature_name = unscaled_inputs.columns.values

In [49]:
# use the coefficients from this table (they will be exported later and will be used in Tableau)
# transpose the model coefficients (model.coef_) and throws them into a df (a vertical organization, so that they can be
# multiplied by certain matrices later) 
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

# add the coefficient values to the summary table
summary_table['Coefficient'] = np.transpose(reg.coef_)

# display the summary table
summary_table

Feature name  Coefficient
0                  Reason 1     2.074526
1                  Reason 2     0.333558
2                  Reason 3     1.559230
3                  Reason 4     1.328933
4    Transportation Expense     0.704860
5          Distance to Work    -0.036825
6                       Age    -0.199931
7   Daily Work Load Average    -0.003197
8           Body Mass Index     0.322704
9                 Education    -0.332304
10                 Children     0.383986
11                     Pets    -0.332164
12              Month Value     0.188939
13          Day of the week    -0.071354

In [50]:
# do a little Python trick to move the intercept to the top of the summary table
# move all indices by 1
summary_table.index = summary_table.index + 1

# add the intercept at index 0
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

# sort the df by index
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.166909
1                  Reason 1     2.074526
2                  Reason 2     0.333558
3                  Reason 3     1.559230
4                  Reason 4     1.328933
5    Transportation Expense     0.704860
6          Distance to Work    -0.036825
7                       Age    -0.199931
8   Daily Work Load Average    -0.003197
9           Body Mass Index     0.322704
10                Education    -0.332304
11                 Children     0.383986
12                     Pets    -0.332164
13              Month Value     0.188939
14          Day of the week    -0.071354

## Interpreting the coefficients

In [51]:
# create a new Series called: 'Odds ratio' which will show the.. odds ratio of each feature
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [52]:
# display the df
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.166909    0.846276
1                  Reason 1     2.074526    7.960773
2                  Reason 2     0.333558    1.395926
3                  Reason 3     1.559230    4.755158
4                  Reason 4     1.328933    3.777010
5    Transportation Expense     0.704860    2.023564
6          Distance to Work    -0.036825    0.963845
7                       Age    -0.199931    0.818787
8   Daily Work Load Average    -0.003197    0.996808
9           Body Mass Index     0.322704    1.380857
10                Education    -0.332304    0.717270
11                 Children     0.383986    1.468125
12                     Pets    -0.332164    0.717369
13              Month Value     0.188939    1.207967
14          Day of the week    -0.071354    0.931132

In [53]:
# sort the table according to odds ratio
# note that by default, the sort_values method sorts values by 'ascending'
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Reason 1     2.074526    7.960773
3                  Reason 3     1.559230    4.755158
4                  Reason 4     1.328933    3.777010
5    Transportation Expense     0.704860    2.023564
11                 Children     0.383986    1.468125
2                  Reason 2     0.333558    1.395926
9           Body Mass Index     0.322704    1.380857
13              Month Value     0.188939    1.207967
8   Daily Work Load Average    -0.003197    0.996808
6          Distance to Work    -0.036825    0.963845
14          Day of the week    -0.071354    0.931132
0                 Intercept    -0.166909    0.846276
7                       Age    -0.199931    0.818787
12                     Pets    -0.332164    0.717369
10                Education    -0.332304    0.717270

Reason 1 = Various Diseases

Reason 2 = Pregnancy and giving birth

Reason 3 = Poisoning

Reason 4 = Light Diseases

#### Testing the model

In [54]:
reg.score(x_test,y_test)

0.7357142857142858

Based on the data that the model has never seen, in around 73% of cases, the model predict correctly that if the person is going to be excesively absent

In [58]:
# we need the probability of 0 and 1 
predicted_probability = reg.predict_proba(x_test)
predicted_probability

array([[0.73818406, 0.26181594],
       [0.58978443, 0.41021557],
       [0.36634007, 0.63365993],
       [0.81220479, 0.18779521],
       [0.06146199, 0.93853801],
       [0.30790074, 0.69209926],
       [0.29670107, 0.70329893],
       [0.08157059, 0.91842941],
       [0.80560765, 0.19439235],
       [0.76015779, 0.23984221],
       [0.46268566, 0.53731434],
       [0.15612304, 0.84387696],
       [0.04645643, 0.95354357],
       [0.72518161, 0.27481839],
       [0.23401317, 0.76598683],
       [0.54800338, 0.45199662],
       [0.52970199, 0.47029801],
       [0.55485413, 0.44514587],
       [0.38448275, 0.61551725],
       [0.0254313 , 0.9745687 ],
       [0.69717166, 0.30282834],
       [0.80473679, 0.19526321],
       [0.37908634, 0.62091366],
       [0.40204277, 0.59795723],
       [0.18482564, 0.81517436],
       [0.76088002, 0.23911998],
       [0.47365773, 0.52634227],
       [0.88833741, 0.11166259],
       [0.13622021, 0.86377979],
       [0.79704602, 0.20295398],
       [0.

In [59]:
predicted_probability.shape

(140, 2)

#### Save the model

In [60]:
import pickle

In [61]:
# we need to pickle the reg and the absenteeabsenteeism_scaler
with open ('model', 'wb') as file:
    pickle.dump(reg, file)

In [62]:
with open ('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)